import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"
import { Toaster as SileoToaster } from "sileo";
import { Toaster as HotToaster } from "react-hot-toast";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                {children}
                <SileoToaster
                    position="top-right"
                    offset={20}
                    options={{
                        fill: "#ffffff",
                        roundness: 20,
                        styles: {
                            title: "font-semibold tracking-tight text-slate-900",
                            description: "text-slate-600 leading-relaxed",
                            badge: "shadow-sm",
                            button:
                                "bg-slate-900 text-white hover:bg-slate-700 transition-colors",
                        },
                    }}
                />
                <HotToaster position="top-right" reverseOrder={false} />
            </body>
        </html>
    );
}
